# image will be published to ghcr.io/<user>/<name>
name: adwaitium
# description will be included in the image's metadata
description: My opinionated Universal Blue image, based on silverblue-nvidia

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: containerfile
    snippets:
      - LABEL org.opencontainers.image.source=https://github.com/trevnels/adwaitium
  
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/kylegospo/gnome-vrr/repo/fedora-%OS_VERSION%/kylegospo-gnome-vrr-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nvidia-explicit-sync/repo/fedora-%OS_VERSION%/gloriouseggroll-nvidia-explicit-sync-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/kylegospo/prompt/repo/fedora-%OS_VERSION%/kylegospo-prompt-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/39/tailscale.repo #TODO: wait for tailscale f40 repos
    install:
      - f37-backgrounds-gnome
      - git-credential-libsecret
      - gnome-shell-extension-tailscale-gnome-qs
      - gvfs-nfs
      - nautilus-open-any-terminal
      - papirus-icon-theme
      - tailscale
      - starship
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - gnome-terminal-nautilus
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
      remove:
      # - org.gnome.eog
    user:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
      repo-name: gnome-nightly
      repo-title: "GNOME Nightly" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.gnome.Ptyxis.Devel
      remove:

  - type: script # enable VRR
    scripts:
      # - enable-vrr.sh
      # - install-prompt.sh
      - ext-rounded-window-corners.sh
      
  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - dconf-update-service
      - laptop
      - ublue-update # https://github.com/ublue-os/ublue-update
      
  - type: script
    scripts:
      - config-topgrade.sh
      
  - type: systemd # enable userland init service
    system:
      enabled:
        - userland-init-system.service
        - tailscaled.service
        - ublue-update.timer
      unmasked:
        - userland-init-system.service
    user:
      enabled:
        - userland-init-user.service
      unmasked:
        - userland-init-user.service
  
  - type: fonts # install JetBrainsMono NF
    fonts:
      nerd-fonts:
        - JetBrainsMono
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

